<template>
  <section>
    <div  style="background-color: #636be7">
      <div class="container">
        <navbar />
      </div>
    </div>
    <div class="container" style="margin-top: 50px; margin-bottom: 150px;">
      <h1 class="title">Documentation</h1>

      <figure class="image">
        <img src="../../assets/dymmer_imp.png" alt="dymmer-screen1" />
        <figcaption>Figure 1 - Adding feature model.</figcaption>
      </figure>
      <div class="content text">
        <p>
          Figure 1 illustrates a feature model imported by the tool. Item 1
          highlighted in red is the first step to importing the model. After
          clicking the button, two options will be shown to the user: create a
          model of features or import an existing template. After selecting the
          option to import the model, the user must choose an XML file in one of
          the formats generated by the tool S.P.L.O.T. The imported feature
          model is displayed in the feature editor, as highlighted in item 2 of
          Figure 1. The imported model is based on the demonstration of other
          usage scenarios.
        </p>
      </div>

      <figure class="image">
        <img src="../../assets/fm_modeling.png" alt="dymmer-screen1" />
        <figcaption>Figure 2 - Modeling feature model.</figcaption>
      </figure>
      <div class="content text">
        <p>
          Figure 2 illustrates the modeling of a DSPL feature model. In the
          feature diagram, the entire feature tree of the model is displayed,
          icons represent the types and features relationships, and the
          hierarchy is denoted by the spacing so that the rightmost features are
          descendants of the upper leftmost features. In Figure 2, item 4
          highlights the process of creating, changing and removing features
          through a toolbox that is displayed after the user clicks (with the
          right mouse button) on the feature to be edited.
        </p>
        <p>
          Item 5 in the same figure highlights the module's editing module
          constraints. After the user clicks on the edit constraints button, a
          window will be opened so that constraints can be selected to be
          applied, changed or removed from the model. Finally, item 3 in Figure
          2 highlights the button to save the changes made. When clicking on the
          save button, the model is sent for persistence in the tool repository.
          This process can be performed whenever changes are made to the feature
          model.
        </p>
      </div>

      <figure class="image">
        <img src="../../assets/fm_contexts.png" alt="dymmer-screen1" />
        <figcaption>Figure 3 - Modeling contexts.</figcaption>
      </figure>
      <div class="content text">
        <p>
          The context modeling of the DSPL feature model is illustrated in
          Figure 3. Item 6 highlights the list of available contexts, as well as
          two buttons for creating and validating contexts. In the example,
          editing the LOW BATTERY context is activated, so the tool blocks the
          other items until the context is validated and saved. This process
          helps the user to focus on the active context, highlighting the
          functions that are currently active. Similar to the feature editing
          process, activating, deactivating or deleting context features can be
          done with a toolbox that is activated when the user clicks on the
          feature to be edited. This process is highlighted in item 7 in Figure
          3.
        </p>
      </div>

      <figure class="image">
        <img src="../../assets/fm_measures.png" alt="dymmer-screen1" />
        <figcaption>Figure 4 - Evaluating feature model.</figcaption>
      </figure>
      <div class="content text">
        <p>
          To perform the feature model evaluation process, the user needs to
          click on the Apply Measures tab, as shown in Figure 4. This process is
          relatively simple, item 9 in Figure 4 highlights the button for
          applying the evaluation.
        </p>
        <p>
          After clicking on Reapply Measures, a list containing 38 measures will
          be displayed, the user can select the measures he wants to apply.
          After applying the measures, a list is displayed with the results of
          the feature model evaluation process. This process can be seen in item
          8, as highlighted in Figure 4. Each measure contains an attribute that
          represents the absolute value calculated based on the computation
          rules established for the measure. Also, it returns a threshold, an
          attribute that is computed based on the tool measures repository and
          provides rapid feedback regarding the quality of the feature model.
        </p>
      </div>

      <figure class="image">
        <img src="../../assets/fm_exports.png" alt="dymmer-screen1" />
        <figcaption>Figure 5 - Exporting to XML, CSV and PDF.</figcaption>
      </figure>
      <div class="content text">
        <p>
          Figure 5 highlights the tool's export features. To export the feature
          model to XML, the user must go to the FEATURE MODEL, highlighted by
          item 10, and then click on the button to export the feature model. It
          is only possible to export one model at a time and the user can choose
          between exporting the feature model with or without contexts.
        </p>
        <p>
          The tool also allows the export of results of maintenance measures.
          This function is highlighted by item 11 in Figure 5. The user can
          export the results in PDF or CSV. After clicking on the export
          buttons, the document will be downloaded automatically containing the
          information of the feature model the results of applied measures.
        </p>
      </div>

      <figure class="image">
        <img src="../../assets/dspl-repository.png" alt="dymmer-screen1" />
        <figcaption>Figure 6 - DSPL feature model repository.</figcaption>
      </figure>
      <div class="content text">
        <p>
          Figure 6 illustrates the feature model repository of the tool. The
          repository is divided by type, listing the name of the model, the
          type, the number of features, the author, the source (identifies if it
          was imported from another tool) and the creation date. These
          attributes can also be used to sort the list, as well as it is
          possible to search for a specific model in the search field. Figure 6,
          illustrates the models created or imported in the tool that are
          persisted in a database so that the user can edit the model.
        </p>
      </div>
    </div>
    <div>
      <futer/>
    </div>
  </section>
</template>

<script>
import Navbar from "@/components/Navbar/Navbar.vue";
import Footer from "@/components/Footer/Footer";

export default {
  components: {
    Navbar,
    futer: Footer
  }
};
</script>

<style lang="sass">
.container
  .title
    text-align: center
    font-size: 1.5rem
  .image
    max-width: 700px
    margin: 30px auto
  .content
    text-align: justify
  .text
    max-width: 700px
    margin: 0 auto
</style>
